import type { ModelDescriptor } from '@/services/gateway/types';

const IMAGE_ASPECTS = ['1:1', '3:2', '2:3', '5:4', '4:5', '4:3', '3:4', '16:9', '9:16', '21:9'];
const VIDEO_ASPECTS = ['adaptive', '16:9', '4:3', '1:1', '3:4', '9:16', '21:9'];
const SD20_PRICING = {
  currency: '¥',
  matrix: {
    '480p': 0.6,
    '720p': 1.2,
    native1080p: 3.0,
    '1080p': 1.48,
    '2k': 1.62,
    '4k': 1.83,
  },
};
const SD20_FAST_PRICING = {
  currency: '¥',
  matrix: {
    '480p': 0.5,
    '720p': 1.0,
    '1080p': 1.28,
    '2k': 1.42,
    '4k': 1.63,
  },
};

export const RUNNING_HUB_MODELS: ModelDescriptor[] = [
  {
    id: 'rhart-image-g-2',
    providerId: 'runninghub',
    capability: 'image',
    label: 'rhart-image-g-2',
    caption: '全能图片 G-2.0 · 低价渠道',
    supportsSize: false,
    supportsN: true,
    supportedAspects: IMAGE_ASPECTS,
    pricing: { currency: '¥', flat: 0.1 },
  },
  {
    id: 'rhart-image-g-2-official',
    providerId: 'runninghub',
    capability: 'image',
    label: 'rhart-image-g-2-official',
    caption: '全能图片 G-2.0 · 官方稳定版',
    supportsSize: false,
    supportsN: true,
    supportedAspects: IMAGE_ASPECTS,
    supportedResolutions: ['1K', '2K', '4K'],
    supportedQualityLevels: ['low', 'medium', 'high'],
    pricing: { currency: '¥', matrix: { low: { '1k': 0.29, '2k': 0.42, '4k': 0.96 }, medium: { '1k': 0.37, '2k': 0.89, '4k': 1.32 }, high: { '1k': 1.54, '2k': 2.82, '4k': 4.52 } } },
  },
  {
    id: 'rhart-image-n-pro',
    providerId: 'runninghub',
    capability: 'image',
    label: '全能图片PRO',
    caption: '全能图片 PRO · 低价渠道',
    supportsSize: false,
    supportsN: true,
    supportedAspects: IMAGE_ASPECTS,
    pricing: { currency: '¥', flat: 0.15 },
  },
  {
    id: 'rhart-image-n-pro-official',
    providerId: 'runninghub',
    capability: 'image',
    label: '全能图片PRO · 官方稳定版',
    caption: '全能图片 PRO · 官方稳定版',
    supportsSize: false,
    supportsN: true,
    supportedAspects: IMAGE_ASPECTS,
    supportedResolutions: ['1K', '2K', '4K'],
    supportedQualityLevels: ['low', 'medium', 'high'],
    pricing: { currency: '¥', matrix: { low: { '1k': 0.34, '2k': 0.49, '4k': 1.02 }, medium: { '1k': 0.43, '2k': 0.97, '4k': 1.45 }, high: { '1k': 1.6, '2k': 2.89, '4k': 4.59 } } },
  },
  {
    id: 'rhart-image-n-pro-official-ultra',
    providerId: 'runninghub',
    capability: 'image',
    label: '全能图片PRO · Ultra',
    caption: '全能图片 PRO · 官方 Ultra 高画质版',
    supportsSize: false,
    supportsN: true,
    supportedAspects: IMAGE_ASPECTS,
    supportedResolutions: ['1K', '2K', '4K'],
    pricing: { currency: '¥', matrix: { '1k': 2.0, '2k': 3.5, '4k': 5.5 } },
  },
  {
    id: 'rhart-image-n-g31-flash',
    providerId: 'runninghub',
    capability: 'image',
    label: '全能图片V2',
    caption: '全能图片 V2 · 低价渠道',
    supportsSize: false,
    supportsN: true,
    supportedAspects: IMAGE_ASPECTS,
    pricing: { currency: '¥', flat: 0.12 },
  },
  {
    id: 'rhart-image-n-g31-flash-official',
    providerId: 'runninghub',
    capability: 'image',
    label: '全能图片V2 · 官方稳定版',
    caption: '全能图片 V2 · 官方稳定版',
    supportsSize: false,
    supportsN: true,
    supportedAspects: IMAGE_ASPECTS,
    supportedQualityLevels: ['low', 'medium', 'high'],
    pricing: { currency: '¥', matrix: { low: { '1k': 0.25, '2k': 0.38 }, medium: { '1k': 0.32, '2k': 0.76 }, high: { '1k': 1.25, '2k': 2.3 } } },
  },
  { id: 'sparkvideo-2.0-text', providerId: 'runninghub', capability: 'video', label: 'SD2.0 · 文生视频', caption: 'Seedance-V2 文生视频', supportedAspects: VIDEO_ASPECTS, pricing: SD20_PRICING },
  { id: 'sparkvideo-2.0-image', providerId: 'runninghub', capability: 'video', label: 'SD2.0 · 图生视频', caption: 'Seedance-V2 图生视频', supportedAspects: VIDEO_ASPECTS, pricing: SD20_PRICING },
  { id: 'sparkvideo-2.0-multimodal', providerId: 'runninghub', capability: 'video', label: 'SD2.0 · 全能参考视频', caption: 'Seedance-V2 全能参考视频', supportedAspects: VIDEO_ASPECTS, pricing: SD20_PRICING },
  { id: 'sparkvideo-2.0-fast-text', providerId: 'runninghub', capability: 'video', label: 'SD2.0-Fast · 文生视频', caption: 'Seedance-V2 快速文生视频', supportedAspects: VIDEO_ASPECTS, pricing: SD20_FAST_PRICING },
  { id: 'sparkvideo-2.0-fast-image', providerId: 'runninghub', capability: 'video', label: 'SD2.0-Fast · 图生视频', caption: 'Seedance-V2 快速图生视频', supportedAspects: VIDEO_ASPECTS, pricing: SD20_FAST_PRICING },
  { id: 'sparkvideo-2.0-fast-multimodal', providerId: 'runninghub', capability: 'video', label: 'SD2.0-Fast · 全能参考视频', caption: 'Seedance-V2 快速全能参考视频', supportedAspects: VIDEO_ASPECTS, pricing: SD20_FAST_PRICING },
  { id: 'google/gemini-3.1-pro-preview', providerId: 'runninghub', capability: 'text', label: 'Gemini 3.1 Pro', caption: '复杂推理与创意写作', pricing: { currency: '¥', flat: 0 } },
  { id: 'google/gemini-3.1-flash-lite-preview', providerId: 'runninghub', capability: 'text', label: 'Gemini 3.1 Flash Lite', caption: '快速文本生成与提示词精修', pricing: { currency: '¥', flat: 0 } },
  { id: 'deepseek/deepseek-v4-pro', providerId: 'runninghub', capability: 'text', label: 'DeepSeek V4 Pro', caption: '代码与逻辑能力强', pricing: { currency: '¥', flat: 0 } },
  { id: 'deepseek/deepseek-v4-flash', providerId: 'runninghub', capability: 'text', label: 'DeepSeek V4 Flash', caption: '高性价比文本处理', pricing: { currency: '¥', flat: 0 } },
];
